data:extend({
	-- runtime
	{
		type = "bool-setting",
		name = "recipelister-output",
		order = "a",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-recipe",
		order = "a-a",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-item",
		order = "a-b",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-fluid",
		order = "a-c",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-assembling-machine",
		order = "a-d",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-furnace",
		order = "a-e",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-mining-drill",
		order = "a-f",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-resource",
		order = "a-g",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-transport-belt",
		order = "a-h",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-inserter",
		order = "a-i",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-boiler",
		order = "a-j",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-generator",
		order = "a-k",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-reactor",
		order = "a-l",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-solar-panel",
		order = "a-m",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-lab",
		order = "a-n",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-technology",
		order = "a-o",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-equipment-grid",
		order = "a-p",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-equipment",
		order = "a-q",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-enable-tile",
		order = "a-r",
		setting_type = "runtime-per-user",
		default_value = true,
	},
	{
		type = "bool-setting",
		name = "recipelister-split-output",
		order = "a",
		setting_type = "runtime-per-user",
		default_value = true,
	}
})
